In [1]:
import pandas as pd
df = pd.read_parquet("sinan_animais_peconhentos_2007_2024.parquet")

In [2]:
df

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_SIN_PRI,SEM_PRI,...,COM_SISTEM,COM_RENAL,COM_EDEMA,COM_SEPTIC,COM_CHOQUE,DOENCA_TRA,EVOLUCAO,DT_OBITO,DT_ENCERRA,DT_DIGITA
0,2,X29,20070118,200703,2007,29,2915106,1391,20070118,200703,...,2,,,,,2,1,00000000,20070214,20070228
1,2,X29,20070117,200703,2007,29,2915106,1391,20070117,200703,...,2,,,,,1,1,00000000,20070118,20070124
2,2,X29,20070119,200703,2007,29,2915106,1391,20070119,200703,...,,,,,,1,1,00000000,20070120,20070124
3,2,X29,20070109,200702,2007,29,2915106,1391,20070109,200702,...,2,,,,,2,1,00000000,20070110,20070117
4,2,X29,20070101,200701,2007,29,2915106,1391,20070101,200701,...,9,,,,,9,1,00000000,20070108,20070117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3369916,2,X29,20241229,202501,2024,43,4312203,1611,20241229,202501,...,2,,,,,2,1,,20250102,20250124
3369917,2,X29,20241229,202501,2024,23,2303709,1512,20241229,202501,...,2,,,,,2,1,,20250210,20250220
3369918,2,X29,20241229,202501,2024,42,4218509,1563,20241229,202501,...,2,,,,,2,1,,20241230,20241230
3369919,2,X29,20241229,202501,2024,35,3543709,1337,20241223,202452,...,2,,,,,2,1,,20250102,20250102
3369920,2,X29,20241229,202501,2024,29,2915809,1398,20241229,202501,...,2,,,,,2,1,,20250106,20250107

In [10]:
from pysus import sinan

In [14]:
from pysus import PySUS

async def main():
    async with PySUS() as pysus:
        # Query DuckLake catalog
        files = await pysus.query(
            dataset="sinan",
            group="ANIM",
            
        
        )

        # Download files
        for f in files:
            local = await pysus.download(f)
            print(local.path)

        # Read multiple parquet files
        import glob
        paths = glob.glob("/cache/sinan/**/*.parquet")
        df = pysus.read_parquet(paths, mode="union").df()

ImportError: cannot import name 'PySUS' from 'pysus' (/home/gabrielgraciano/analises_vigitrop/.venv/lib/python3.12/site-packages/pysus/__init__.py)

In [13]:
dados

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_SIN_PRI,SEM_PRI,...,COM_SISTEM,COM_RENAL,COM_EDEMA,COM_SEPTIC,COM_CHOQUE,DOENCA_TRA,EVOLUCAO,DT_OBITO,DT_ENCERRA,DT_DIGITA
0,2,X29,20070118,200703,2007,29,2915106,1391,20070118,200703,...,2,,,,,2,1,00000000,20070214,20070228
1,2,X29,20070117,200703,2007,29,2915106,1391,20070117,200703,...,2,,,,,1,1,00000000,20070118,20070124
2,2,X29,20070119,200703,2007,29,2915106,1391,20070119,200703,...,,,,,,1,1,00000000,20070120,20070124
3,2,X29,20070109,200702,2007,29,2915106,1391,20070109,200702,...,2,,,,,2,1,00000000,20070110,20070117
4,2,X29,20070101,200701,2007,29,2915106,1391,20070101,200701,...,9,,,,,9,1,00000000,20070108,20070117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194409,2,X29,20260327,202612,2026,27,2705101,1534,20260327,202612,...,2,,,,,2,1,,20260331,20260331
194410,2,X29,20260327,202612,2026,41,4119152,1356,20260318,202611,...,2,,,,,2,1,,20260327,20260327
194411,2,X29,20260327,202612,2026,41,4126272,1361,20260325,202612,...,2,,,,,2,1,,20260327,20260327
194412,2,X29,20260327,202612,2026,42,4212601,1560,20260327,202612,...,2,,,,,2,1,,20260330,20260330
194413,2,X29,20260327,202612,2026,42,4218251,1546,20260327,202612,...,2,,,,,2,1,,20260328,20260401

In [ ]:
import pandas as pd

# 1. Carregar os dados de 2007 a 2026
df_all = pd.read_parquet('dados_2007_2026.parquet')

# 2. Remover todas as observações em que o ano é 2024 (usando a coluna NU_ANO)
df_all_filtered = df_all[df_all['NU_ANO'].astype(str) != '2024']

# 3. Carregar os dados corretos de 2024
df_2024 = pd.read_parquet('sinan_animais_peconhentos_2024.parquet')

# 4. Juntar os dois dataframes
dados_corrigidos = pd.concat([df_all_filtered, df_2024], ignore_index=True)

# 5. Salvar o novo dataframe corrigido
dados_corrigidos.to_parquet('dados_corrigidos.parquet')

# Exibir informações do novo dataframe
print(f"Tamanho do dataframe original filtrado: {len(df_all_filtered)}")
print(f"Tamanho do dataframe de 2024 inserido: {len(df_2024)}")
print(f"Tamanho final de dados_corrigidos: {len(dados_corrigidos)}")
dados_corrigidos.head()